#!/bin/bash
#NOTA Sin testear en real!! teño que marchar.

#NOTA Esto esta bien así porque quiero tener el contenido completo de la configuracion de xorg.conf para ambos modos de trabajo guardados en algun sitio, en este 
#   caso, en las variables xorg_XXXXmode_conf.

#TODO Si tal para proximas veriones en vez de guardar toda la configuracion de ambos modos en variables, podemos hacer que simplemente se comente/descomente
#   la linea (Option         "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3")
#   que bloquea powermizer en la configuracion para intercambiar el modo de trabajo.

ruta_xorg_conf="/home/diego/Documentos/BashWorkSpace/desarrollos/xorg.conf";

xorg_perfmode_conf='
	#Performance Mode Custom Config
	# nvidia-settings: X configuration file generated by nvidia-settings
	# nvidia-settings:  version 331.20  (buildd@roseapple)  Mon Feb  3 15:07:22 UTC 2014

	# nvidia-xconfig: X configuration file generated by nvidia-xconfig
	# nvidia-xconfig:  version 352.63  (buildmeister@swio-display-x64-rhel04-11)  Sat Nov  7 22:00:19 PST 2015
	
	Section "ServerLayout"
	    Identifier     "Layout0"
	    Screen      0  "Screen0" 0 0
	    InputDevice    "Keyboard0" "CoreKeyboard"
	    InputDevice    "Mouse0" "CorePointer"
	    Option         "Xinerama" "0"
	EndSection
	
	Section "Files"
	EndSection
	
	Section "InputDevice"
	
	    # generated from default
	    Identifier     "Mouse0"
	    Driver         "mouse"
	    Option         "Protocol" "auto"
	    Option         "Device" "/dev/psaux"
	    Option         "Emulate3Buttons" "no"
	    Option         "ZAxisMapping" "4 5"
	EndSection
	
	Section "InputDevice"
	
	    # generated from default
	    Identifier     "Keyboard0"
	    Driver         "kbd"
	EndSection
	
	Section "Monitor"
	
	    # HorizSync source: edid, VertRefresh source: edid
	    Identifier     "Monitor0"
	    VendorName     "Unknown"
	    ModelName      "HSP LM02"
	    HorizSync       30.0 - 83.0
	    VertRefresh     55.0 - 75.0
	    Option         "DPMS"
	EndSection
	
	Section "Device"
	    Identifier     "Device0"
	    Driver         "nvidia"
	    VendorName     "NVIDIA Corporation"
	    BoardName      "GeForce GTX 550 Ti"
	    Option         "Coolbits" "1"
	EndSection
	
	Section "Screen"
	
	# Removed Option "metamodes" "DVI-I-1: nvidia-auto-select +1920+0, HDMI-0: nvidia-auto-select +0+0"
	# Removed Option "metamodes" "HDMI-0: nvidia-auto-select +0+0"
	# Removed Option "metamodes" "DVI-I-1: nvidia-auto-select +1920+0, HDMI-0: nvidia-auto-select +0+0"
	# Removed Option "metamodes" "HDMI-0: nvidia-auto-select +0+0"
	    Identifier     "Screen0"
	    Device         "Device0"
	    Monitor        "Monitor0"
	    DefaultDepth    24
	    Option         "Stereo" "0"
	    Option         "nvidiaXineramaInfoOrder" "DFP-1"
	    Option         "metamodes" "DVI-I-1: NULL, HDMI-0: nvidia-auto-select +0+0"
	    Option         "SLI" "Off"
	    Option         "MultiGPU" "Off"
	    Option         "BaseMosaic" "off"
	    SubSection     "Display"
	        Depth       24
	    EndSubSection
	EndSection';

xorg_savemode_conf='
	#Save Mode Custom Config
	# nvidia-settings: X configuration file generated by nvidia-settings
	# nvidia-settings:  version 331.20  (buildd@roseapple)  Mon Feb  3 15:07:22 UTC 2014
	
	# nvidia-xconfig: X configuration file generated by nvidia-xconfig
	# nvidia-xconfig:  version 352.63  (buildmeister@swio-display-x64-rhel04-11)  Sat Nov  7 22:00:19 PST 2015
	
	Section "ServerLayout"
	    Identifier     "Layout0"
	    Screen      0  "Screen0" 0 0
	    InputDevice    "Keyboard0" "CoreKeyboard"
	    InputDevice    "Mouse0" "CorePointer"
	    Option         "Xinerama" "0"
	EndSection
	
	Section "Files"
	EndSection
	
	Section "InputDevice"
	
	    # generated from default
	    Identifier     "Mouse0"
	    Driver         "mouse"
	    Option         "Protocol" "auto"
	    Option         "Device" "/dev/psaux"
	    Option         "Emulate3Buttons" "no"
	    Option         "ZAxisMapping" "4 5"
	EndSection
	
	Section "InputDevice"
	
	    # generated from default
	    Identifier     "Keyboard0"
	    Driver         "kbd"
	EndSection
	
	Section "Monitor"
	
	    # HorizSync source: edid, VertRefresh source: edid
	    Identifier     "Monitor0"
	    VendorName     "Unknown"
	    ModelName      "HSP LM02"
	    HorizSync       30.0 - 83.0
	    VertRefresh     55.0 - 75.0
	    Option         "DPMS"
	EndSection
	
	Section "Device"
	    Identifier     "Device0"
	    Driver         "nvidia"
	    VendorName     "NVIDIA Corporation"
	    BoardName      "GeForce GTX 550 Ti"
	    Option         "Coolbits" "1"
	    #La siguiente opcion bloquea powermizer al nivel inferior de rendimiento, se hace para evitar el bug de los drivers nVidia que bloquean el rendimiento al maximo nivel en dual screen
	    Option         "RegistryDwords" "PowerMizerEnable=0x1; PerfLevelSrc=0x2222; PowerMizerLevel=0x3; PowerMizerDefault=0x3; PowerMizerDefaultAC=0x3"
	EndSection
	
	Section "Screen"
	
# Removed Option "metamodes" "DVI-I-1: nvidia-auto-select +1920+0, HDMI-0: nvidia-auto-select +0+0"
# Removed Option "metamodes" "HDMI-0: nvidia-auto-select +0+0"
# Removed Option "metamodes" "DVI-I-1: nvidia-auto-select +1920+0, HDMI-0: nvidia-auto-select +0+0"
# Removed Option "metamodes" "HDMI-0: nvidia-auto-select +0+0"
	    Identifier     "Screen0"
	    Device         "Device0"
	    Monitor        "Monitor0"
	    DefaultDepth    24
	    Option         "Stereo" "0"
	    Option         "nvidiaXineramaInfoOrder" "DFP-1"
	    Option         "metamodes" "DVI-I-1: NULL, HDMI-0: nvidia-auto-select +0+0"
	    Option         "SLI" "Off"
	    Option         "MultiGPU" "Off"
	    Option         "BaseMosaic" "off"
	    SubSection     "Display"
	        Depth       24
	    EndSubSection
	EndSection';


#Todo: Pedir respuesta de confirmacion del usuario
#ToDo: Preguntar al usuario si quiere reiniciar el gestor de ventanas ("restart lightdm" en el caso de XFCE)

if grep -q "Performance Mode" $ruta_xorg_conf
then
    echo "Se ha detectado el modo Rendimiento activo";
    read -p "¿Quieres activar el modo ahorro?(s/N)" -n 1 -r choice
	echo    # (optional) move to a new line
	if [[ $choice =~ ^[Ss]$ ]]
	then
	    > $ruta_xorg_conf;
	    echo $xorg_savemode_conf > $ruta_xorg_conf;
	    echo "Se ha activado el modo ahorro"; 
	else
	    echo "Bye!";
        exit 0;    
	fi
elif grep -q "Save Mode" $ruta_xorg_conf
then
    echo "Se ha detectado el modo ahorro activo";
    read -p "¿Quieres activar el modo rendimiento?(s/N)" -n 1 -r choice
	echo    # (optional) move to a new line
	if [[ $choice =~ ^[Ss]$ ]]
	then
	    > $ruta_xorg_conf;
	    echo $xorg_perfmode_conf > $ruta_xorg_conf;
	    echo "Se ha activado el modo rendimiento"; 
	else
	    echo "Bye!";
        exit 0;    
	fi	
else
	echo "No se ha podido detectar el modo de trabajo de la Tarjeta de video, comprueba que la configuracion de video en $ruta_xorg_conf";	
fi

#Yes/No Dialog - Implementar en ifs

exit 0